# Data cleaning
This cleaning file is created to join and clean data for happiness 2015-2017 and 2018-2019

In [1]:
import pandas as pd
import clean

## 2015 - 2017

In [2]:
#load 2015 data
load_happy15 = pd.read_csv('../data/raw-data/Happiness-Score/2015.csv')
happy15 = load_happy15.drop(['Happiness Rank','Standard Error'],axis=1)

# rename col
happy15.rename(columns={'Happiness Score':'happiness_score','Economy (GDP per Capita)':'GDP_per_cap','Health (Life Expectancy)':'life_expect','Trust (Government Corruption)':'gov_trust','Dystopia Residual':'dystopia_residual'},inplace=True)

# create continent col
clean.create_continent(happy15) 

# adding year col
happy15['Year'] = "2015"

happy15.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"

,Country,Region,happiness_score,GDP_per_cap,Family,life_expect,Freedom,gov_trust,Generosity,dystopia_residual,continent,Year
0,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,Europe,2015
1,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,Europe,2015
2,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,Europe,2015
3,Norway,Western Europe,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,Europe,2015
4,Canada,North America,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,America,2015

In [3]:
#load 2016 data
load_happy16 = pd.read_csv('../data/raw-data/Happiness-Score/2016.csv')
happy16 = load_happy16.drop(['Happiness Rank','Lower Confidence Interval', 'Upper Confidence Interval'],axis=1)

# rename col
happy16.rename(columns={'Happiness Score':'happiness_score','Economy (GDP per Capita)':'GDP_per_cap','Health (Life Expectancy)':'life_expect','Trust (Government Corruption)':'gov_trust','Dystopia Residual':'dystopia_residual'},inplace=True)

# create continent col
clean.create_continent(happy16)

# adding year
happy16['Year'] = "2016"

happy16.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"

,Country,Region,happiness_score,GDP_per_cap,Family,life_expect,Freedom,gov_trust,Generosity,dystopia_residual,continent,Year
0,Denmark,Western Europe,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,Europe,2016
1,Switzerland,Western Europe,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,Europe,2016
2,Iceland,Western Europe,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,Europe,2016
3,Norway,Western Europe,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465,Europe,2016
4,Finland,Western Europe,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596,Europe,2016

In [4]:
# load 2017 data
load_happy17 = pd.read_csv('../data/raw-data/Happiness-Score/2017.csv')
happy17 = load_happy17.drop(['Happiness.Rank','Whisker.high', 'Whisker.low'],axis=1)

# rename col
happy17.rename(columns={'Happiness.Score':'happiness_score','Economy..GDP.per.Capita.':'GDP_per_cap','Health..Life.Expectancy.':'life_expect','Trust..Government.Corruption.':'gov_trust','Dystopia.Residual':'dystopia_residual'},inplace=True)

happy17.head()

,Country,happiness_score,GDP_per_cap,Family,life_expect,Freedom,Generosity,gov_trust,dystopia_residual
0,Norway,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [5]:
# clean hongkong and taiwan cell
clean.hongkong(happy17,False)
clean.taiwan(happy17,False)

# adding region and continent for year 2017
clean.create_region(happy16,happy17)
clean.create_continent(happy17)

# adding year for 2017
happy17['Year'] = "2017"

happy17.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Hong Kong"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Taiwan"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = from_table['Region'][j]
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = "TBD"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "TBD"

,Country,happiness_score,GDP_per_cap,Family,life_expect,Freedom,Generosity,gov_trust,dystopia_residual,Region,continent,Year
0,Norway,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,Western Europe,Europe,2017
1,Denmark,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,Western Europe,Europe,2017
2,Iceland,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,Western Europe,Europe,2017
3,Switzerland,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,Western Europe,Europe,2017
4,Finland,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182,Western Europe,Europe,2017

In [6]:
# re arrange all col for appending
clean.arrange_col_15_17(happy15)
clean.arrange_col_15_17(happy16)
clean.arrange_col_15_17(happy17)

# appending 2015, 2016, 2017
happy1517 = happy15.append(happy16,ignore_index=True).append(happy17,ignore_index=True)

In [7]:
clean.delete_less_than_record(happy1517,3)

['Belize', 'Central African Republic', 'Comoros', 'Djibouti', 'Laos', 'Lesotho', 'Mozambique', 'Namibia', 'Oman', 'Puerto Rico', 'Somalia', 'Somaliland Region', 'Somaliland region', 'South Sudan', 'Suriname', 'Swaziland']

In [8]:
happy1517.to_csv('../data/clean-data/clean-happiness-15-17_using python.csv', index=False)

## 2018 - 2019

In [9]:
#load 2018 data
load_happy18 = pd.read_csv('../data/raw-data/Happiness-Score/2018.csv')
load_happy18.head()
happy18 = load_happy18.drop(['Overall rank'],axis=1)

# rename col
happy18.rename(columns={'Country or region':'Country','Score': 'happiness_score','GDP per capita':'GDP_per_cap','Social support':'social_support','Healthy life expectancy':'life_expect','Freedom to make life choices': 'Freedom','Perceptions of corruption':'corruption_perceptions'},inplace=True)

# adding year col
happy18['Year'] = "2018"

# clean hongkong and taiwan cell
clean.hongkong(happy18,False)
clean.taiwan(happy18,False)

happy18.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Hong Kong"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Taiwan"

,Country,happiness_score,GDP_per_cap,social_support,life_expect,Freedom,Generosity,corruption_perceptions,Year
0,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,2018
1,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,2018
2,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2018
3,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,2018
4,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,2018

In [10]:
#load 2019 data
load_happy19 = pd.read_csv('../data/raw-data/Happiness-Score/2019.csv')
load_happy19.head()
happy19 = load_happy19.drop(['Overall rank'],axis=1)

# rename col
happy19.rename(columns={'Country or region':'Country','Score': 'happiness_score','GDP per capita':'GDP_per_cap','Social support':'social_support','Healthy life expectancy':'life_expect','Freedom to make life choices': 'Freedom','Perceptions of corruption':'corruption_perceptions'},inplace=True)

# adding year col
happy19['Year'] = "2019"


# clean hongkong and taiwan cell
clean.hongkong(happy19,False)
clean.taiwan(happy19,False)

happy19.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Hong Kong"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Taiwan"

,Country,happiness_score,GDP_per_cap,social_support,life_expect,Freedom,Generosity,corruption_perceptions,Year
0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

In [11]:
# arrange col for appending
clean.arrange_col_18_19(happy18)
clean.arrange_col_18_19(happy19)

happy1819 = happy18.append(happy19,ignore_index=True)

In [12]:
# removing countries with missing record
clean.delete_less_than_record(happy1819,2)

['Angola', 'Belize', 'Comoros', 'Gambia', 'Macedonia', 'North Macedonia', 'Sudan', 'Swaziland']

In [13]:
happy1819.to_csv('../data/clean-data/clean-happiness-18-19_using python.csv', index=False)

## 2015 - 2019

In [14]:
# adding region and continent for year 2018 and 2019
clean.create_region(happy17,happy18)
clean.create_region(happy17,happy19)

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = from_table['Region'][j]
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = "TBD"

In [15]:
clean.create_continent(happy18)
clean.create_continent(happy19)

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "TBD"

In [16]:
# arrange col for appending
clean.arrange_col_18_19(happy18)
clean.arrange_col_18_19(happy19)

happy1819 = happy18.append(happy19,ignore_index=True)

In [17]:
trim_1517 = happy1517.drop(['Family','gov_trust','dystopia_residual'],axis=1)
trim_1819 = happy1819.drop(['social_support','corruption_perceptions'],axis=1)

clean.arrange_col_15_19(trim_1517)
clean.arrange_col_15_19(trim_1819)

happy1519 = trim_1517.append(trim_1819,ignore_index=True)

clean.delete_less_than_record(happy1519,5)
trim_1517.head()

['Angola', 'Belize', 'Central African Republic', 'Comoros', 'Gambia', 'Laos', 'Lesotho', 'Macedonia', 'Mozambique', 'Namibia', 'North Cyprus', 'North Macedonia', 'Northern Cyprus', 'Somalia', 'South Sudan', 'Sudan', 'Swaziland', 'Trinidad & Tobago', 'Trinidad and Tobago']

,Country,Region,happiness_score,GDP_per_cap,life_expect,Freedom,Generosity,continent,Year
0,Switzerland,Western Europe,7.587,1.39651,0.94143,0.66557,0.29678,Europe,2015
1,Iceland,Western Europe,7.561,1.30232,0.94784,0.62877,0.43630,Europe,2015
2,Denmark,Western Europe,7.527,1.32548,0.87464,0.64938,0.34139,Europe,2015
3,Norway,Western Europe,7.522,1.45900,0.88521,0.66973,0.34699,Europe,2015
4,Canada,North America,7.427,1.32629,0.90563,0.63297,0.45811,America,2015

In [18]:
happy1519.to_csv('../data/clean-data/clean-happiness-15-19_using python.csv', index=False)

# Merging data for Hannah and Rachel

In [19]:
# read rachel data
rachel = pd.read_csv('../data/clean-data/Clean Happiness Score 15-17.csv')

# rename col
rachel.rename(columns={'Happiness Score':'happiness_score','Economy (GDP per Capita)':'GDP_per_cap','Health (Life Expectancy)':'life_expect','Trust (Government Corruption)':'gov_trust','Dystopia Residual':'dystopia_residual'},inplace=True)

# create continent col
clean.create_continent(rachel) 

rachel.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "

,Country,Region,Year,happiness_score,GDP_per_cap,Family,life_expect,Freedom,gov_trust,Generosity,dystopia_residual,continent
0,Afghanistan,Southern Asia,2015,3.58,0.32,0.30,0.30,0.23,0.10,0.37,1.95,Asia
1,Albania,Central and Eastern Europe,2015,4.96,0.88,0.80,0.81,0.36,0.06,0.14,1.90,Europe
2,Algeria,Middle East and Northern Africa,2015,5.61,0.94,1.08,0.62,0.29,0.17,0.08,2.43,Africa
3,Angola,Sub-Saharan Africa,2015,4.03,0.76,0.86,0.17,0.10,0.07,0.12,1.95,Africa
4,Argentina,Latin America and Caribbean,2015,6.57,1.05,1.25,0.79,0.45,0.08,0.11,2.84,America

In [20]:
rachel.shape

(444, 12)

In [21]:
#load hannah data
hannah = pd.read_csv('../data/clean-data/Clean Happiness Score 18-19.csv')

# rename col
hannah.rename(columns={'Country or region':'Country','Score': 'happiness_score','GDP per capita':'GDP_per_cap','Healthy life expectancy':'life_expect','Freedom to make life choices': 'Freedom','Perceptions of corruption':'corruption_perceptions'},inplace=True)

# clean hongkong and taiwan cell
clean.hongkong(hannah,False)
clean.taiwan(hannah,False)

# adding reagion and continent
clean.create_region(rachel,hannah)
clean.create_continent(hannah) 

hannah.head()

C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Hong Kong"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["Country"][i] = "Taiwan"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = from_table['Region'][j]
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_table['Region'][i] = "TBD"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Asia"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Europe"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Africa"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "America"
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "Oceania "
C:\Users\Home\Desktop\huy\comp2200\github\group-project-group-4\codes\clean.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table['continent'][i] = "TBD"

,Country,Year,happiness_score,GDP_per_cap,life_expect,Freedom,Generosity,corruption_perceptions,Unnamed: 8,Region,continent
0,Afghanistan,2018,3.632,0.332,0.255,0.085,0.191,0.036,NaN,Southern Asia,Asia
1,Afghanistan,2019,3.203,0.350,0.361,0.000,0.158,0.025,NaN,Southern Asia,Asia
2,Albania,2018,4.586,0.916,0.790,0.419,0.149,0.032,NaN,Central and Eastern Europe,Europe
3,Albania,2019,4.719,0.947,0.874,0.383,0.178,0.027,NaN,Central and Eastern Europe,Europe
4,Algeria,2018,5.295,0.979,0.687,0.077,0.055,0.135,NaN,Middle East and Northern Africa,Africa

In [22]:
trim_rachel = rachel.drop(['Family','gov_trust','dystopia_residual'],axis=1)
trim_hannah = hannah.drop(['corruption_perceptions'],axis=1)

clean.arrange_col_15_19(trim_rachel)
clean.arrange_col_15_19(trim_hannah)

rachel_hannah = trim_rachel.append(trim_hannah,ignore_index=True)

rachel_hannah.shape

(748, 10)

In [23]:
clean.delete_less_than_record(rachel_hannah,5)
print(rachel_hannah.shape)

['Angola', 'Central African Republic', 'Laos', 'Lesotho', 'Macedonia', 'Mozambique', 'Namibia', 'North Cyprus', 'Northern Cyprus', 'Somalia', 'South Sudan', 'Sudan', 'Trinidad & Tobago', 'Trinidad and Tobago']
(715, 10)

In [24]:
rachel_hannah.to_csv('../data/clean-data/Clean Happiness Score 15-19.csv', index=False)